[[mgr.prepend_keymap]]
on = "!"
for = "unix"
run = 'shell "$SHELL" --block'
desc = "Open $SHELL here"
[[mgr.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"
[[mgr.prepend_keymap]]
on = "F"
run = "plugin smart-filter"
desc = "Smart filter"
[[mgr.prepend_keymap]]
on = "p"
run = "plugin smart-paste"
desc = "Paste into the hovered directory or CWD"

[[mgr.prepend_keymap]]
on = "J"
run = "plugin jump-to-char"
desc = "Jump to char"

[[mgr.prepend_keymap]]
on = "<C-d>"
run = "plugin diff"
desc = "Diff the selected with the hovered file"

[[mgr.prepend_keymap]]
on = "\\"
run = "plugin quicklook"
desc = "QuickLook file/dir"

## TODO find a way to open explore then quit yazi automatically
[[mgr.prepend_keymap]]
on = "e"
run = "shell -- explorer.exe . & pkill yazi"
desc = "Open with Explor "

[[mgr.prepend_keymap]]
on = "<Enter>"
run = "shell -- xdg-open $@ & pkill yazi"
desc = "Open the selected files"

## TODO find a way to open a file then auto quit yazi

# [[mgr.prepend_keymap]]
# on = "<C-y>"
# run = "plugin system-clipboard"
# desc = "Copy to system clipboard"
